name: app_kamus_daerah_sahu_tala_i
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  cloud_firestore: ^4.13.4
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  firebase_core: ^2.24.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
