// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-3ullBNVWfJNVcK21cUQC8ChSNOQ-5k',
    appId: '1:734717496789:web:b7b2f03a3c1689b8fe815c',
    messagingSenderId: '734717496789',
    projectId: 'appkamussahu',
    authDomain: 'appkamussahu.firebaseapp.com',
    storageBucket: 'appkamussahu.appspot.com',
    measurementId: 'G-NJHZ303PB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmNb1-AHS91TqrifUsff5XSqFbnPdRvI',
    appId: '1:734717496789:android:e4162c199a0e7371fe815c',
    messagingSenderId: '734717496789',
    projectId: 'appkamussahu',
    storageBucket: 'appkamussahu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxZ_f2GBsw_FQaFnPqcswrELcvzqmp9JA',
    appId: '1:734717496789:ios:7bda3d0aa7897fcbfe815c',
    messagingSenderId: '734717496789',
    projectId: 'appkamussahu',
    storageBucket: 'appkamussahu.appspot.com',
    iosBundleId: 'com.example.appKamusDaerahSahuTalai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxZ_f2GBsw_FQaFnPqcswrELcvzqmp9JA',
    appId: '1:734717496789:ios:96e9b05efa8e452dfe815c',
    messagingSenderId: '734717496789',
    projectId: 'appkamussahu',
    storageBucket: 'appkamussahu.appspot.com',
    iosBundleId: 'com.example.appKamusDaerahSahuTalai.RunnerTests',
  );
}
